"""add is_admin to users

Revision ID: 518dcdcd7dbf
Revises: 42c3195f991d
Create Date: 2026-06-19 17:18:39.293350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '518dcdcd7dbf'
down_revision: Union[str, Sequence[str], None] = '42c3195f991d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('reset_token_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_hash')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
