"""V2 - Init postgres and tables

Revision ID: 5541330a4216
Revises: 
Create Date: 2026-03-10 09:13:15.934518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5541330a4216'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=True),
    sa.Column('bookmaker', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('selection', sa.String(), nullable=True),
    sa.Column('odds_taken', sa.Float(), nullable=True),
    sa.Column('stake', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('clv', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bets_id'), 'bets', ['id'], unique=False)
    op.create_table('odds_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('bookmaker', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('home_odds', sa.Float(), nullable=True),
    sa.Column('draw_odds', sa.Float(), nullable=True),
    sa.Column('away_odds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_history_id'), 'odds_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odds_history_id'), table_name='odds_history')
    op.drop_table('odds_history')
    op.drop_index(op.f('ix_bets_id'), table_name='bets')
    op.drop_table('bets')
    # ### end Alembic commands ###
