"""Add MatchTeamStatistics and Match.sofascore_event_id

Revision ID: 8ddc048fe228
Revises: 5541330a4216
Create Date: 2026-06-14 22:04:58.124428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ddc048fe228'
down_revision: Union[str, Sequence[str], None] = '5541330a4216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_team_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('possession_pct', sa.Float(), nullable=True),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('big_chances', sa.Integer(), nullable=True),
    sa.Column('big_chances_scored', sa.Integer(), nullable=True),
    sa.Column('big_chances_missed', sa.Integer(), nullable=True),
    sa.Column('shots_total', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('shots_off_target', sa.Integer(), nullable=True),
    sa.Column('shots_blocked', sa.Integer(), nullable=True),
    sa.Column('shots_inside_box', sa.Integer(), nullable=True),
    sa.Column('shots_outside_box', sa.Integer(), nullable=True),
    sa.Column('corners', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('passes_total', sa.Integer(), nullable=True),
    sa.Column('passes_accurate', sa.Integer(), nullable=True),
    sa.Column('final_third_entries', sa.Integer(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('recoveries', sa.Integer(), nullable=True),
    sa.Column('clearances', sa.Integer(), nullable=True),
    sa.Column('goalkeeper_saves', sa.Integer(), nullable=True),
    sa.Column('goals_prevented', sa.Float(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('duels_won_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_team_statistics_id'), 'match_team_statistics', ['id'], unique=False)
    op.create_index(op.f('ix_match_team_statistics_match_id'), 'match_team_statistics', ['match_id'], unique=False)
    op.add_column('matches', sa.Column('sofascore_event_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_matches_sofascore_event_id'), 'matches', ['sofascore_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_sofascore_event_id'), table_name='matches')
    op.drop_column('matches', 'sofascore_event_id')
    op.drop_index(op.f('ix_match_team_statistics_match_id'), table_name='match_team_statistics')
    op.drop_index(op.f('ix_match_team_statistics_id'), table_name='match_team_statistics')
    op.drop_table('match_team_statistics')
    # ### end Alembic commands ###
