"""Add TeamCharacteristic table

Revision ID: df57f4d6adb8
Revises: 518dcdcd7dbf
Create Date: 2026-08-20 15:29:53.774663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df57f4d6adb8'
down_revision: Union[str, Sequence[str], None] = '518dcdcd7dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('offensive_strength', sa.Float(), nullable=True),
    sa.Column('defensive_solidity', sa.Float(), nullable=True),
    sa.Column('motivation', sa.Float(), nullable=True),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index(op.f('ix_team_characteristics_id'), 'team_characteristics', ['id'], unique=False)
    op.drop_index('ix_world_cup_team_stats_id', table_name='world_cup_team_stats')
    op.drop_table('world_cup_team_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_cup_team_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('matches_played', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goals_for', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goals_against', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wins', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('draws', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='world_cup_team_stats_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='world_cup_team_stats_pkey'),
    sa.UniqueConstraint('team_id', name='world_cup_team_stats_team_id_key')
    )
    op.create_index('ix_world_cup_team_stats_id', 'world_cup_team_stats', ['id'], unique=False)
    op.drop_index(op.f('ix_team_characteristics_id'), table_name='team_characteristics')
    op.drop_table('team_characteristics')
    # ### end Alembic commands ###
